Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -139,7 +139,7 @@ jobs:
           
           # Function to convert read-only EXT4 image to read-write
           ro_ext4_img_to_rw() {
-              resize_img "$1" "$(($(du --apparent-size -sB512 "$1" | cut -f1) * 2))"s || return 1
+              resize_img "$1" "$(($(du --apparent-size -sB512 "$1" | cut -f1) * 2 * 512))" || return 1
               e2fsck -fp -E unshare_blocks "$1" || return 1
               resize_img "$1" || return 1
               return 0
@@ -153,8 +153,8 @@ jobs:
           echo "Mount images"
           
           sudo mkdir -p "$ROOT_MNT"
-          sudo mount -vo loop "$WSA_PATH/system.img" "$ROOT_MNT"
-          sudo mount -vo loop "$WSA_PATH/vendor.img" "$VENDOR_MNT"
+          sudo mount -t ext4 -o loop "$WSA_PATH/system.img" "$ROOT_MNT" || abort "Failed to mount system.img"
+          sudo mount -t ext4 -o loop "$WSA_PATH/vendor.img" "$VENDOR_MNT" || abort "Failed to mount vendor.img"
           
           echo -e "Mount done\n"
           
